name: Build and deploy Python app to Azure Web App - leave-assistant

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Create and activate virtualenv
        run: |
          python -m venv venv
          source venv/bin/activate

      - name: Install dependencies (excluding MCP)
        run: |
          python -m pip install-- upgrade pip
          pip install fastapi uvicorn
          pip install "git+https://${{ secrets.GH_TOKEN }}@github.com/ModularCommandProtocol/mcp.git#egg=mcp"

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: leave-assistant
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE }}
          package: .
