name: Build and deploy Python app to Azure Web App - leave-assistant

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Create and activate virtualenv
      run: |
        python -m venv venv
        source venv/bin/activate

    - name: Install dependencies (excluding MCP)
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt || true  # ignore failure if MCP is missing

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.YOUR_CLIENT_ID_SECRET_NAME }}
          tenant-id: ${{ secrets.YOUR_TENANT_ID_SECRET_NAME }}
          subscription-id: ${{ secrets.YOUR_SUBSCRIPTION_ID_SECRET_NAME }}


      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: leave-assistant
          slot-name: production
          package: .
